# Generated by Django 3.0.3 on 2020-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_auto_20200319_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(default='notrequested', max_length=20),
        ),
    ]
