# Generated by Django 3.0.3 on 2020-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='Empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='Empty', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20),
        ),
    ]
