# Generated by Django 3.0.3 on 2020-03-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20200316_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='avatars/default.jpg', null=True, upload_to='pics'),
        ),
    ]
